#!/bin/bash
# Humanoid Sandvich Dispenser

echo "$PWD/$1"

if [ "$1" == "" ]; then
  echo "vscode: Missing argument 1"
  exit 1
fi

if [ ! -f "$PWD/$1" ]; then # If the file does not exist, create it before attempting to open.
  read -p "vscode: $1 does not exist. Would you like to create the file? Y/N " yn
  case $yn in
    [Yy]* ) touch "$1"; break;;
    [Nn]* ) exit 0;;
    * ) exit 1;;
  esac
fi

IFS='/'
PWD_NEW=""
read -ra DIR <<< "$PWD"

for i in "${!DIR[@]}"; do
  if [ $i -gt 2 ]; then 
    PWD_NEW="$PWD_NEW/${DIR[$i]}"
  elif [ $i -gt 1 ]; then
    PWD_NEW="${DIR[$i]}"
  fi
done

start "vscode://file/$PWD_NEW/$1"