#! /bin/sh
#
# bspwmrc
# Copyright (C) 2021 sandvich <sandvich@sandvich-pc>
#
# Distributed under terms of the MIT license.
#

# set default color scheme before starting other programs
colorscheme.sh gruvbox

if ! pgrep -x "sxhkd" > /dev/null; then
    sxhkd &
fi

if ! pgrep -x "compton" > /dev/null; then
    compton --backend glx &
fi

if ! pgrep -x "polybar" > /dev/null; then
    if [ "$(hostname)" = "manjaro" ]; then
        polybar -c ~/.config/polybar-config/config main &
        ln -s /tmp/polybar_mqueue.$! /tmp/ipc-mainbar # for sending msg by name
        polybar -c ~/.config/polybar-config/config alt &
        ln -s /tmp/polybar_mqueue.$! /tmp/ipc-altbar
    else
        polybar -c ~/.config/polybar-config/config minibar &
    fi
    #[ "$(hostname)" = "manjaro"] && polybar -c ~/.config/polybar-config/config main & || polybar -c ~/.config/polybar-config/config minibar &
fi

# Some machines use dunst instead of the default notification daemon
if ! pgrep -x "dunst" > /dev/null && which "dunst" > /dev/null; then 
    start-dunst.sh &
fi

if ! pgrep -x "mpd" > /dev/null; then
    mpd &
fi

if ! pgrep -x "mpd-notification" > /dev/null && which "mpd-notification" > /dev/null; then
    mpd-notification -H localhost -p 7700 -t 2 &
fi

if ! pgrep -x "clipman"; then
    clipman &
fi

xcape -e "Super_L=Escape"

# BSPWM Configuration

bspc monitor primary -d web code misc discord game VI VII VIII
bspc monitor any -d alt

bspc config border_width         4
bspc config window_gap           8
#bspc config active_border_color  "#D5C4A1"
#bspc config normal_border_color  "#282828"
#bspc config focused_border_color  "#928374"
if [[ $(hostname) == "manjaro" ]]; then # hostname "manjaro" has a status bar height of 48
    bspc config top_padding      40
else
    bspc config top_padding      28
fi

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false

bspc config ignore_ewmh_focus    true # stop stealing focus

bspc rule -a Gimp desktop=VI state=floating follow=on
bspc rule -a firefox desktop=web
bspc rule -a discord desktop=discord
bspc rule -a element desktop=discord
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a yakuake state=floating follow=on
bspc rule -a latte-dock state=floating follow=on
bspc rule -a plasma state=floating
bspc rule -a plasmashell state=floating border=off focus=off
bspc rule -a Zathura state=tiled
bspc rule -a st-floating state=floating
bspc rule -a st-dialog focus=on state=floating layer=above
bspc rule -a st-dropdown sticky=on state=floating hidden=on rectangle=800x600+560+200
bspc rule -a *:*:minecraft-launcher state=floating rectangle=240x700+160+0 # don't ask what this is
bspc rule -a Pavucontrol state=floating follow=on
