#! /bin/sh

if ! pgrep -x "sxhkd" > /dev/null; then
	sxhkd &
fi

if ! pgrep -x "compton" > /dev/null; then
	compton --backend glx &
fi

if ! pgrep -x "polybar" > /dev/null; then
	polybar --reload main &
fi

if ! pgrep -x "dunst" > /dev/null && which "dunst" > /dev/null; then # Some of my machines use dunst
	dunst &
fi

if ! pgrep -x "mpd" > /dev/null; then
	mpd &
fi

if ! pgrep -x "mpd-notification" > /dev/null; then
	mpd-notification -H localhost -p 7700 -t 2 &
fi

xcape -e "Super_L=Escape"

# BSPWM Configuration

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         2
bspc config window_gap           4
bspc config active_border_color  "#D5C4A1"
bspc config normal_border_color  "#303030"
bspc config focused_border_color  "#928374"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a yakuake state=floating follow=on
bspc rule -a latte-dock state=floating follow=on
bspc rule -a plasma state=floating
bspc rule -a plasmashell state=floating border=off focus=off
bspc rule -a Zathura state=tiled
bspc rule -a st-floating state=floating
bspc rule -a st-dialog focus=on state=floating layer=above
